language: node_js
node_js:
- '8.4'
before_script:
- npm install -g @angular/cli
- npm install
script:
- ng test
cache:
  directories:
  - node_modules
notifications:
  email:
  - tuomas.jaakola@iki.fi
