language: node_js
node_js:
- '8'
# Use Chrome with Karma
apt:
  sources:
  - google-chrome
  packages:
  - google-chrome-stable
  - google-chrome-beta
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- npm install -g @angular/cli
script:
- ng lint
- ng test --single-run
- ng build --env=prod
# Rename dist to filemaps-webui and make a build pkg
- mv dist filemaps-webui
- tar cvzf filemaps-webui-build.tar.gz filemaps-webui/
cache:
  directories:
  - node_modules
notifications:
  email:
  - tuomas.jaakola@iki.fi
deploy:
  provider: releases
  api_key:
    secure: XWj4C1EnG/owc1Zz3HyN2GTNoUWNAVP9S5rilWUJFPRX1oPC6CgbtwNQDk/p3FuEFx/AweMhieMlogamPNYBivoK81YWPI7DHfs6uK3bXiQ2dK4J/+uFaN/pISIRzmLIwWiFmRdc8bbhEX8DXcRE7RTyebDCRIbxvspfDOcgzj1lZo9bl6MC0VoqrxtCllhLi36XYegsltt2eB5mKqCKH+U2U6cKb5uLbq+xzOQCCy7Weew/HwEEY7Ox9PmwTE8avr/wLk5CXNsfRjHZh9aIfLMKvoa1p8z3nq/tXIwXyVdAzhWqEa7oPpDAM2x4fyPbsyLckiP/Vdsf+nIJ66gmGVdwfh/3O3MQi7qw2VVVui6GLrMePQ3nRZFmwbe+fiJfQpX+D1nVfIANXiPEljphYV68PsX13XogPQas1kFX31hQl5lQ3MvhqPrNZfTlMwoRfY3KMUZukvXdn/KxDdDsT2AxuWEXY+7ikk2OeIfVb3cLz34H7zQ1oFUsNtg2DRIGEjQrEmKoDru7y71f3yGaEwP6xXU7CqdZfSH1kRK6nF7t0R0vNvSq/Od5qILwlaqrGCRCGLGOflFmel0Z0PZG1Vbb6CX3Sg6XN8qzEzo6H5AQKcMyowwH4kkl6kQJeYed7fimGiyY5PrxKNIvLPPDVJnoCVre9vN+bpHUAdCtFtk=
  file: filemaps-webui-build.tar.gz
  skip_cleanup: true
  on:
    tags: true
    repo: filemaps/filemaps-webui
